### PR TITLE
Add missing 'Adwaita' cursors to the container

### PR DESCRIPTION
**Pull request by Scony**
Required by https://github.com/WebKit/WebKit/pull/27024

### CODE REVIEW

**Comment by TingPing** [comment]
The theme is already mounted to `/usr/local/share/icons`.

We need to figure out why it’s not working.

**Comment by TingPing** [comment]
Can you try setting the `XCURSOR_PATH` env var to include the `/usr/local` paths?

**Comment by Scony** [comment]
> Can you try setting the `XCURSOR_PATH` env var to include the `/usr/local` paths?

I'll try

**Comment by Scony** [comment]
> Can you try setting the `XCURSOR_PATH` env var to include the `/usr/local` paths?

It does not change anything. The "cursor lookup" algorithm we have in WebKit starts from `/usr/local/share/icons/default` anyway.

The problem is that even though we use `/usr/local/share/icons/default` to find the theme (which we do) following symlinks (`/usr/local/share/icons/default/index.theme` -> `/etc/alternatives/x-cursor-theme` -> `/usr/share/icons/Adwaita/cursor.theme`) we cannot find cursor icons under `/usr/share/icons/Adwaita/cursors`. This is because the cursors are part of `adwaita-icon-theme-full` package, see:
```
$ apt-file list adwaita-icon-theme-full
(...)
adwaita-icon-theme-full: /usr/share/icons/Adwaita/cursors/arrow
adwaita-icon-theme-full: /usr/share/icons/Adwaita/cursors/bd_double_arrow
adwaita-icon-theme-full: /usr/share/icons/Adwaita/cursors/bottom_left_corner
adwaita-icon-theme-full: /usr/share/icons/Adwaita/cursors/bottom_right_corner
adwaita-icon-theme-full: /usr/share/icons/Adwaita/cursors/bottom_side
adwaita-icon-theme-full: /usr/share/icons/Adwaita/cursors/bottom_tee
(...)
```

**Comment by TingPing** [comment]
So ideally we didn't ship any part of Adwaita in the image, but it seems to be a hard dependency on a ton of things.

This works `ln -s /usr/local/share/icons/Adwaita/cursors/ /usr/share/icons/Adwaita/cursors`

**Review by nikolaszimmermann — APPROVED** [review]

**Comment by nikolaszimmermann** [comment]
Oops did not intentionally to approve sorry

**Pull request closed without merging**
